<a href="https://colab.research.google.com/github/imsumin018/ML_hackerrank/blob/main/oneHot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [2]:
obj = {'student_id' : ['s1', 's2', 's3', 's4', 's5', 's6'],
       'score': [55,90,85,71,63,99]}
       

In [3]:
df = pd.DataFrame(obj)

In [4]:
df


student_id  score
0         s1     55
1         s2     90
2         s3     85
3         s4     71
4         s5     63
5         s6     99

In [5]:
df['grade'] = pd.cut(df['score'], bins = [0,60,70,80,90,100], labels= ['가','양', '미', '우' , '수'])

In [6]:
df

student_id  score grade
0         s1     55     가
1         s2     90     우
2         s3     85     우
3         s4     71     미
4         s5     63     양
5         s6     99     수

In [7]:
lb_encoder = LabelEncoder()
lb_encoder.fit(df['grade'])
lb_labels = lb_encoder.transform(df['grade'])
print(lb_labels)

[0 4 4 1 3 2]


In [9]:
lb_encoder.classes_

array(['가', '미', '수', '양', '우'], dtype=object)

In [10]:
lb_labels_2d = lb_labels.reshape(-1, 1)#2d Label;

In [11]:
lb_labels_2d

array([[0],
       [4],
       [4],
       [1],
       [3],
       [2]])

In [12]:
oh_encoder = OneHotEncoder(sparse=False)

In [13]:
oh_encoder.fit(lb_labels_2d)

/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(sparse=False, sparse_output=False)

In [15]:
oh_lables=  oh_encoder.transform(lb_labels_2d)

In [16]:
oh_lables

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])